export const DIMENSION = {
  CURIOSITY: 'curiosity',
  SOCIAL: 'social',
  SELF_DISCIPLINE: 'self-discipline',
  EMOTION: 'emotion',
  COOPERATION: 'cooperation',
  BALANCED: 'balanced',
  STRUCTURED: 'structured',
  FREE_RANGED: 'free-ranged',
  PACE: 'pace',
  SENSITIVITY: 'sensitivity',
  FOCUS: 'focus',
};

export const CATEGORY = {
  A: [
    DIMENSION.CURIOSITY,
    DIMENSION.SOCIAL,
    DIMENSION.COOPERATION,
    DIMENSION.SELF_DISCIPLINE,
    DIMENSION.EMOTION,
  ],
  S: [DIMENSION.BALANCED, DIMENSION.STRUCTURED, DIMENSION.FREE_RANGED],
  K: [DIMENSION.PACE, DIMENSION.FOCUS, DIMENSION.SENSITIVITY],
};

export const DIMENSION_TEXT = {
  [DIMENSION.CURIOSITY]: '求知力',
  [DIMENSION.SOCIAL]: '社交力',
  [DIMENSION.SELF_DISCIPLINE]: '自控力',
  [DIMENSION.EMOTION]: '情绪调节力',
  [DIMENSION.COOPERATION]: '合作力',
  [DIMENSION.BALANCED]: '和谐型',
  [DIMENSION.STRUCTURED]: '结构型',
  [DIMENSION.FREE_RANGED]: '自由型',
  [DIMENSION.PACE]: '行为节奏',
  [DIMENSION.SENSITIVITY]: '情绪敏感度',
  [DIMENSION.FOCUS]: '专注自律',
};
